### PR TITLE
Simplify `DF.distinct/2` with groups

### PR DESCRIPTION
**Pull request by philss**
This makes the `distinct/2` function consider the columns from groups as
columns to distinct.

This also makes the DF keep the columns of groups, displaying the groups
in the final dataframe.

### CODE REVIEW

**Comment by philss** [comment]
@josevalim @cigrainger do you think this behaviour is correct?
I couldn't make the previous version work with groups, so I don't know if this should work like this.

**Comment by cigrainger** [comment]
Yes the behaviour is correct. I don't think we should tie the top level API to this particular implementation though. I think this one should be more like #253 -- and we should let the different backends handle the implementation.

**Comment by philss** [comment]
> I think this one should be more like https://github.com/elixir-nx/explorer/pull/253 -- and we should let the different backends handle the implementation.

I changed to make this a responsibility of the native code. The only difference is that the columns were in different order, but the result was the same. This looks fine. WDYT?

**Review by cigrainger — APPROVED** [review]
Love it! This should end up being way faster too. I think we should start migrating the grouped tests to the grouped test file I created (@josevalim's suggestion) but that doesn't have to happen in this PR.

:shipit:

**Comment by philss** [comment]
> This should end up being way faster too.

I'm not sure if it is faster, but is certainly more clear on both sides now :D 

>  I think we should start migrating the grouped tests to the grouped test file I created (@josevalim's suggestion) but that doesn't have to happen in this PR.

I moved them to this new file. Thanks for the advice!

**Pull request merged**
