### PR TITLE
Do fewer passes on cols while inspecting

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Review by cigrainger — APPROVED** [review]
🎉🎉🎉🎉🎉💕

**Comment by cigrainger** [comment]
Oh this is probably a silly question @josevalim but how do we get rid of the quotation marks around the ellipses?

**Comment by josevalim** [comment]
In `opts` there is a `:limit` field. Set it to 5 and let container_doc add the `...` for you. :)

**Comment by josevalim** [comment]
Ah, you will also need to slice 6 elements.

**Pull request merged**
