### PR TITLE
Now fill_missing supports values as strategies

### LINKED ISSUE #63: Support `Series.fill_missing/2` also accepting a fixed scalar fill value
I've got a `DataFrame` loaded with a pile of `nils` and would like to be able set those to a fixed value per the `Series.fill_missing/2` function:

```elixir
df["X10"] |> Series.fill_missing(0.0)
```

Currently that function only accepts atoms referencing internal algorithms and raises an exception when passed a scalar.  Let me know if you need anything else or if I can help in any way.

Thanks!

### PR DESCRIPTION
**Pull request by kimjoaoun**
As the name of the branch suggests, this PR closes #63.

Now the function supports `Integers`,`Floats` and `Strings`.

Note that it'll break if you try to `Explorer.Series.fill_missing()` a series that has a type `a` with a value ("strategy") of type `b`.  Example:

```Ex
iex> s = Explorer.Series.from_list([1.0, 2.0, nil, 4.0])    
iex> Explorer.Series.fill_missing(s, 3)
```

It is returning an error because I'm not sure if we should make a type conversion without the user explicit command. I think it is better returning an error and then letting the user decides if it wants to cast the series to another data type.

Edit:

Do you have any suggestions on making this code more compact? Or do you think this isn't necessary?

### CODE REVIEW

**Review by cigrainger — COMMENTED** [review]
No real advice for making it more compact. Maybe a macro, rust-side? 

E.g.

```rust
macro_rules! init_fill_none {
  ($name:ident, $type:ty, $cast_type:expr) => {
    #[rustler:nif]
    pub fn $name(data: ExSeries, strategy: $type) -> Result<ExSeries, ExplorerError> {
      let s = &data.resource.0;
      let s = s.$cast_type()?.fill_null_with_values(strategy)?.into_series();
      Ok(ExSeries::new(s))
    }
  };
}

init_fill_none!(s_fill_none_with_int, i64, i64)
init_fill_none!(s_fill_none_with_float, f64, f64)
init_fill_none!(s_fill_none_with_str, &str, utf8)
```

You could plausibly split up `fill_missing` with guards instead of the `cond` statement but that would only really give you two lines and they're not particularly meaningful. As in: `def fill_missing(series, strategy) when is_float(strategy), do: ...`.

It might be worth adding a sentence to the docstring for `fill_missing` that says something along the lines of:
> If a scalar value is provided instead of a strategy atom, `nil` will be replaced with that value. It must be of the same dtype as the series.

**Comment by kimjoaoun** [comment]
Hi @cigrainger,
when I tried a small adaptation of your code the compilar screamed at me saying that the operation wasn't allowed.

The following code:

```
macro_rules! init_fill_none {
    ($name:ident, $type:ty, $cast_type:ident) => {
        #[rustler::nif]
        pub fn $name(data: ExSeries, strategy: $type) -> Result<ExSeries, ExplorerError> {
            let s = &data.resource.0;
            let s = s.$cast_type()?.fill_null_with_values(strategy)?.into_series();
            Ok(ExSeries::new(s))
        }
    };
}

init_fill_none!(s_fill_none_with_int, i64, i64);
init_fill_none!(s_fill_none_with_float, f64, f64);
```

Results in the error below:

```

error: custom attribute panicked
  --> src/series.rs:40:9
   |
40 |         #[rustler::nif]
   |         ^^^^^^^^^^^^^^^
...
51 | init_fill_none!(s_fill_none_with_float, f64, f64);
   | ------------------------------------------------- in this macro invocation
   |
   = help: message: unsupported input given: Group(TypeGroup { group_token: Group, elem: Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "f64", span: #0 bytes(24853..24856) }, arguments: None }] } }) })
   = note: this error originates in the macro `init_fill_none` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `explorer` due to previous error
```

**Comment by kimjoaoun** [comment]
Hi @cigrainger,
when I tried a small adaptation of your code the compilar screamed at me saying that the operation wasn't allowed.

The following code:

```
macro_rules! init_fill_none {
    ($name:ident, $type:ty, $cast_type:expr) => {
        #[rustler::nif]
        pub fn $name(data: ExSeries, strategy: $type) -> Result<ExSeries, ExplorerError> {
            let s = &data.resource.0;
            let s = s.$cast_type()?.fill_null_with_values(strategy)?.into_series();
            Ok(ExSeries::new(s))
        }
    };
}

init_fill_none!(s_fill_none_with_float, f64, f64);
```

Results in the error below:

```
error: unexpected token: `f64`
  --> src/series.rs:43:23
   |
43 |             let s = s.$cast_type()?.fill_null_with_values(strategy)?.into_series();
   |                       ^^^^^^^^^^
...
51 | init_fill_none!(s_fill_none_with_float, f64, f64);
   | ------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `init_fill_none` (in Nightly builds, run with -Z macro-backtrace for more info)

error: expected one of `.`, `;`, `?`, `else`, or an operator, found `f64`
  --> src/series.rs:43:23
   |
43 |             let s = s.$cast_type()?.fill_null_with_values(strategy)?.into_series();
   |                       ^^^^^^^^^^ expected one of `.`, `;`, `?`, `else`, or an operator
...
51 | init_fill_none!(s_fill_none_with_float, f64, f64);
   | ------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `init_fill_none` (in Nightly builds, run with -Z macro-backtrace for more info)

error: custom attribute panicked
  --> src/series.rs:40:9
   |
40 |         #[rustler::nif]
   |         ^^^^^^^^^^^^^^^
...
51 | init_fill_none!(s_fill_none_with_float, f64, f64);
   | ------------------------------------------------- in this macro invocation
   |
   = help: message: unsupported input given: Group(TypeGroup { group_token: Group, elem: Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "f64", span: #0 bytes(24852..24855) }, arguments: None }] } }) })
   = note: this error originates in the macro `init_fill_none` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by cigrainger** [comment]
Ah, sorry. I think it should be `ident` instead of `expr` but let me pull this branch and try it.

**Comment by cigrainger** [comment]
Huh. It definitely should be `ident`. I'm not sure why it's not working. Fine to skip for now and revisit, unless you're very hungry to figure it out :).

**Comment by kimjoaoun** [comment]
I tried to find a solution but I couldn't. I think we should come back later.

**Comment by cigrainger** [comment]
Yeah no problemo. Then I think just adding a bit to the docs will do it. :+1:

**Review by cigrainger — APPROVED** [review]
Perfect. Thanks!

**Pull request merged**
