### PR TITLE
Upgrade to polars 0.23

### PR DESCRIPTION
**Pull request by joshuataylor**
This means we can merge https://github.com/elixir-nx/explorer/pull/270 !

Lots of great changes from arrow2: https://github.com/jorgecarleitao/arrow2/releases/tag/v0.13.0

And from polars: https://github.com/pola-rs/polars/releases/tag/rust-polars-v0.23.0

### CODE REVIEW

**Comment by josevalim** [comment]
Awesome!

do we also need to bump the SIMD library or something?

**Comment by philss** [comment]
> do we also need to bump the SIMD library or something?

Maybe we need to bump the nightly version we are using. Arrow2 is using a version that is 2 days newer then ours: https://github.com/jorgecarleitao/arrow2/blob/3b9d86bfb65bc786bf9315a41737a77895716443/.github/workflows/test.yml#L186

**Comment by cigrainger** [comment]
Yep that sounds right to me @philss.

**Comment by joshuataylor** [comment]
Cool, yeah bumped to that version and seems to be good now.

**Pull request merged**
