### PR TITLE
Add `DF.summarise_with/2` that accepts lazy series

### PR DESCRIPTION
**Pull request by philss**
This is a version of `summarise` that works with lazy series in a
callback function. The main difference is that more complex expressions
can be made, and each aggregation must be named.

### CODE REVIEW

**Comment by philss** [comment]
PS: this still WIP. I'm going to finish tomorrow.
But would be nice to have your opinion on how the API should look like. Is this what you expected? 
I mean, like in the test: https://github.com/elixir-nx/explorer/pull/301/files#diff-a8dbae367a98eddc4049331a0ddc27690a3c9441ce21c663024f7d917cce9df5R229-R235

**Comment by josevalim** [comment]
Beautiful!

**Comment by philss** [comment]
@josevalim I think this is it. But we have some operations that don't work only for aggregations, like `:first, :last and :count`, that I skipped. We also have the `:n_unique` aggregation that does not have a correspondent function at `Series`, but have `n_distinct` that seems to do the same - we may need to rename one of them. I'm planning to tackle these missing gaps in another PR. WDYT?

**Comment by josevalim** [comment]
@philss what do you mean about first/last/count not working only for aggregations? where else are they allowed?

**Review by josevalim — APPROVED** [review]

**Comment by josevalim** [comment]
Btw, let's go with `n_distinct` so it mirrors `DataFrame.distinct` (confirmed with @cigrainger). There are also other renames in https://github.com/elixir-nx/explorer/issues/289#issuecomment-1191134730, so we can likely tackle it all at once.

**Comment by philss** [comment]
> what do you mean about first/last/count not working only for aggregations? where else are they allowed?

@josevalim they are allowed in the common series. What I wanted to say is that they are not exclusive for aggregations. So using, for example, `Series.count(ldf["column"])` can work for both grouped and ungrouped DFs.

**Pull request merged**
