### PR TITLE
Use resource binaries on Series.to_list for strings

### PR DESCRIPTION
**Pull request by josevalim**
Still WIP, depends on https://github.com/rusterlium/rustler/pull/485.

### CODE REVIEW

**Comment by josevalim** [comment]
If you folks are OK with cargo temporarily having a Git dependency, this is good to go.

Compared to the latest release, main encodes a utf-8 series to list 10x faster and uses twice less memory.

**Comment by josevalim** [comment]
Note: this PR also has the foundation so we get zero-copy interop with Nx.

**Review by philss — APPROVED** [review]
> If you folks are OK with cargo temporarily having a Git dependency, this is good to go.

> Compared to the latest release, main encodes a utf-8 series to list 10x faster and uses twice less memory.

Awesome! :D 
I'm OK with using the GitHub version :)

**Review by cigrainger — APPROVED** [review]
Incredible. I'm definitely okay with the git dependency!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
