### PR TITLE
Add Trigonometric functions `Series.sin/1`, `Series.cos/1` and `Series.tan/1`

### PR DESCRIPTION
**Pull request by sasikumar87**

### CODE REVIEW

**Comment by josevalim** [comment]
Beautiful @sasikumar87!!! Can you also please add a test here, similar to the log one? https://github.com/elixir-nx/explorer/blob/f61eea719c1f7dcc309cd31d61139c0ce6409041/test/explorer/data_frame_test.exs#L1254

I think a single test for all three options is enough. :)

**Comment by sasikumar87** [comment]
@josevalim already added at https://github.com/elixir-nx/explorer/pull/558/files#diff-c78443a116d7830abea1be0cfb846cecbadf7b223b13f6c630ff39d082ead5f4R1292-R1313 . Or am I missing something?

**Comment by josevalim** [comment]
Sorry, I missed them. :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
