### PR TITLE
Reading data from url example

### PR DESCRIPTION
**Pull request by srowley**
Here is a working example of a solution to address #91. I tried a few things to DRY out the Rust side but got stuck because I don't really know Rust at all. Welcome suggestions for improvement.

### CODE REVIEW

**Comment by cigrainger** [comment]
Looking good! I should be able to give this a proper review tomorrow morning (AEST). Seems like we could expose `Explorer.DataFrame.from_binary/2` to complement `Explorer.DataFrame.to_binary/1`, calling `read_csv_from_memory` directly.

**Comment by cigrainger** [comment]
@josevalim totally agree. The fetching part is somewhat trivial and keeping it out of the API keeps it more flexible.

**Comment by josevalim** [comment]
I have created #167 to discuss the APIs here: #116.

**Comment by josevalim** [comment]
Closing in favor of #186.

**Pull request closed without merging**
