### PR TITLE
Bump rustler_precompiled to v0.5.2

### PR DESCRIPTION
**Pull request by Benjamin-Philip**
Rustler Precompiled had a bug in v0.5.1 wherein precompiled NIFs could not run on Fedora and RHEL machines. See
https://github.com/philss/rustler_precompiled/issues/30

This commit bumps Rustler Precompiled to v0.5.2 to eliminate this bug in explorer.

### CODE REVIEW

**Review by philss — COMMENTED** [review]
Just that comment and :ship:

**Comment by Benjamin-Philip** [comment]
Done.

**Comment by philss** [comment]
@Benjamin-Philip thank you! :purple_heart:  
FYI there is no need to release a new version of this one because the users can just run `mix deps.update rustler_precompiled`, or force reinstallation if using `Mix.install/2` (`Mix.install([:explorer], force: true)`).

**Comment by Benjamin-Philip** [comment]
> @Benjamin-Philip thank you! :purple_heart:  
> FYI there is no need to release a new version of this one because the users can just run `mix deps.update rustler_precompiled`, or force reinstallation if using `Mix.install/2` (`Mix.install([:explorer], force: true)`).

I wasn't going to ask you to release a new version. 🙂

The only reason I asked you to release a new version of `html5ever` was so that I can update Floki, to attempt a contribution.

**Pull request merged**
